name: 'StartOS SDK'
description: 'Provides start-cli'
runs:
  using: 'composite'
  steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: |
        sudo rm /etc/apt/sources.list.d/microsoft-prod.list
        sudo apt-get update
        sudo apt-get install -y git build-essential openssl libssl-dev libc6-dev clang libclang-dev ca-certificates curl jq
        sudo snap install yq deno
        cargo install --force toml-cli web-static-pack-packer
        cargo install --git=https://github.com/Start9Labs/md-packer.git --branch=main
      shell: bash

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Install start-cli
      run: |
        ARCH=$(uname -m)
        OS=$(uname -s | tr '[:upper:]' '[:lower:]')
        if [ "$ARCH" = "x86_64" ]; then
          ARCH_NAME="x86_64"
        elif [ "$ARCH" = "aarch64" ]; then
          ARCH_NAME="aarch64"
        fi
        if [ "$OS" = "linux" ]; then
          OS_NAME="unknown-linux-gnu"
        elif [ "$OS" = "darwin" ]; then
          OS_NAME="apple-darwin"
        fi
        ASSET_NAME="start-cli-${ARCH_NAME}-${OS_NAME}.tar.gz"
        LATEST_RELEASE_URL=$(curl -s https://api.github.com/repos/Start9Labs/start-cli/releases/latest | jq -r '.assets[] | select(.name=="'$ASSET_NAME'") | .browser_download_url')
        curl -L $LATEST_RELEASE_URL -o start-cli.tar.gz
        tar xzf start-cli.tar.gz
        sudo mv start-cli /usr/local/bin/
        rm start-cli.tar.gz
      shell: bash
