name: "StartOS SDK"
description: "Provides start-cli"
runs:
  using: "composite"
  steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v4
      with:
        node-version: "22"

    - name: Install dependencies
      run: |
        sudo rm -f /etc/apt/sources.list.d/microsoft-prod.list
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          build-essential \
          clang \
          libclang-dev \
          squashfs-tools-ng \
          qemu-user-static
      shell: bash

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker
      uses: docker/setup-docker-action@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Install start-cli
      run: |
        ARCH=$(uname -m)
        OS=$(uname -s | tr '[:upper:]' '[:lower:]')
        if [ "$ARCH" = "x86_64" ]; then
          ARCH_NAME="x86_64"
        elif [ "$ARCH" = "aarch64" ]; then
          ARCH_NAME="aarch64"
        fi
        if [ "$OS" = "linux" ]; then
          OS_NAME="unknown-linux-gnu"
        elif [ "$OS" = "darwin" ]; then
          OS_NAME="apple-darwin"
        fi
        BINARY_NAME="start-cli-${ARCH_NAME}-${OS_NAME}"
        ASSET_NAME="${BINARY_NAME}.tar.gz"
        LATEST_RELEASE_URL=$(curl -s https://api.github.com/repos/Start9Labs/start-cli/releases/latest | jq -r '.assets[] | select(.name=="'$ASSET_NAME'") | .browser_download_url')
        curl -L $LATEST_RELEASE_URL -o start-cli.tar.gz
        tar xzf start-cli.tar.gz
        sudo mv $BINARY_NAME /usr/local/bin/start-cli
        rm start-cli.tar.gz
      shell: bash
